# Generated by Django 4.1.4 on 2023-05-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='solded',
            field=models.IntegerField(default=0),
        ),
    ]
