# Generated by Django 4.1.7 on 2023-04-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='mediafiles/product_image'),
        ),
    ]
