# Generated by Django 4.1.4 on 2023-05-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_solded'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off_price',
            field=models.IntegerField(default=0),
        ),
    ]
