# Generated by Django 4.1.4 on 2023-04-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_sold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={},
        ),
    ]
