"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import urllib.parse
from decouple import config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1',
    cast=lambda v: [host.strip() for host in v.split(',') if host.strip()],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'accounts',
    'store',
    'carts',
    'order',
    "phonenumber_field",
    #'admin_honeypot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
]

#SESSION_EXPIRE_SECONDS = 3600  # after X sec user will bw logged out
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_TIMEOUT_REDIRECT = 'accounts/login'

ROOT_URLCONF = 'shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.menu_links',
                'carts.context_processors.counter',
            ],
        },
    },
]

WSGI_APPLICATION = 'shop.wsgi.application'

AUTH_USER_MODEL="accounts.Accounts"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
#
# Configured from environment variables.
# Preferred: set DATABASE_URL, e.g.
#   postgresql://store:store_password@localhost:5432/store
# If DATABASE_URL is unset, falls back to individual DB_* variables, then to a
# local SQLite file for zero-configuration development.

def _env(name, default=None, **kwargs):
    """Read an env value via decouple, treating empty strings as unset."""
    value = config(name, default=None, **kwargs)
    if value is None or value == '':
        return default
    return value


def _database_config():
    """Build the DATABASES['default'] dict from environment variables."""
    url = _env('DATABASE_URL')
    if url:
        parsed = urllib.parse.urlparse(url)
        if parsed.scheme in ('postgres', 'postgresql'):
            return {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': parsed.path.lstrip('/'),
                'USER': urllib.parse.unquote(parsed.username or ''),
                'PASSWORD': urllib.parse.unquote(parsed.password or ''),
                'HOST': parsed.hostname or 'localhost',
                'PORT': parsed.port or '5432',
            }
        if parsed.scheme == 'sqlite':
            return {'ENGINE': 'django.db.backends.sqlite3', 'NAME': parsed.path.lstrip('/')}
        raise ImproperlyConfigured(f'Unsupported DATABASE_URL scheme: {parsed.scheme!r}')

    engine = _env('DB_ENGINE', default='django.db.backends.sqlite3')
    cfg = {'ENGINE': engine, 'NAME': _env('DB_NAME', default=str(BASE_DIR / 'db.sqlite3'))}
    if engine.endswith('postgresql'):
        cfg.update({
            'USER': _env('DB_USER', default=''),
            'PASSWORD': _env('DB_PASSWORD', default=''),
            'HOST': _env('DB_HOST', default='localhost'),
            'PORT': _env('DB_PORT', default='5432'),
        })
    return cfg


DATABASES = {
    'default': _database_config(),
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR , 'staticfiles')
STATICFILES_DIRS=(os.path.join(BASE_DIR,'static'),)


from django.contrib.messages import constants as messages

MESSAGE_TAGS ={
    messages.ERROR:'danger',
}

EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='your-email@gmail.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='your-app-password')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')