# Generated by Django 4.1.7 on 2023-04-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_product_image'),
        ('carts', '0002_alter_cartitems_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carts',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
