# Generated by Django 4.1.4 on 2023-04-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
