# Generated by Django 4.1.4 on 2023-04-19 11:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_accounts_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
