# Generated by Django 5.2.17 on 2026-09-10 09:42

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_accounts_phone_number'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='is_admin',
            new_name='is_superuser',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='addres',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='is_superadmin',
        ),
        migrations.AddField(
            model_name='accounts',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='OTPChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login'), ('PHONE_CHANGE', 'Phone change'), ('RECOVERY', 'Account recovery')], max_length=20)),
                ('code_hash', models.CharField(max_length=128)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('expires_at', models.DateTimeField()),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['phone_number', 'purpose', 'expires_at', 'consumed_at'], name='accounts_ot_phone_n_5a3a15_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('consumed_at__isnull', True), ('locked_until__isnull', True)), fields=('phone_number', 'purpose'), name='unique_active_otp_per_phone_purpose')],
            },
        ),
    ]
