# Generated by Django 4.1.4 on 2023-04-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_order_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='post_price',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
